version: "3.5"
services:
  db:
    image: mariadb:10.3
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./mysql-dump/database.sql:/docker-entrypoint-initdb.d/database.sql
    network_mode: bridge
  app:
    build:
      args:
        user: thainam
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile
    image: microservice
    container_name: microservice-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    links:
      - db
    depends_on:
      - db
    network_mode: bridge
