-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 19:54:14 2020
-- Model: Microservice   Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema microservice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `microservice` ;

-- -----------------------------------------------------
-- Schema microservice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `microservice` DEFAULT CHARACTER SET utf8mb4;
USE `microservice` ;

-- -----------------------------------------------------
-- Table `microservice`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microservice`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `microservice`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microservice`.`jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(180) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT(3) UNSIGNED NOT NULL,
  `reserved_at` INT(10) UNSIGNED NULL DEFAULT NULL,
  `available_at` INT(10) UNSIGNED NOT NULL,
  `created_at` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_index` (`queue` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `microservice`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microservice`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `microservice`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microservice`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(60) NOT NULL,
  `type` ENUM('J', 'F') NOT NULL COMMENT 'J = Pessoa Jurídica; F = Pessoa Física.',
  `cpf` VARCHAR(14) NOT NULL,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `wallet` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `type_INDEX` (`type` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Fake inserts for `microservice`.`users`
-- -----------------------------------------------------
INSERT INTO `microservice`.`users` (`fullname`, `type`, `cpf`, `cnpj`, `email`, `password`, `wallet`)
VALUES
('João Pedro Oliveira', 'F', '654.495.480-28', NULL, 'jpoliveira@teste.com.br', '$2y$10$lI9tj99Js1db/TkFGLKhLOM0bnUt1YmhqzQnqP79R9qHbNsr2u7xq', 250),
('Mauro Silva Pereira', 'F', '545.381.810-72', NULL, 'maurosilva@teste.com.br', '$2y$10$ykN/ZPOxcrGwSOH8hgNdfef/dhAWJTfVAc7qTsE9HiXIVRaYnLKGi', 0),
('Daniele Batista', 'F', '381.707.060-84', NULL, 'danibatista@teste.com.br', '$2y$10$egZ9uF3rwvN/Yz15.KBmJePtfPP4LGGggr115dMjBbZlm4Z2WvnGC', 450),
('Andrea e Cecília Lavanderia Ltda', 'J', '913.002.330-01', '97.738.582/0001-40', 'andreaececilialavanderia@teste.com.br', '$2y$10$Hbq2BVxfeVlVncQuigqjgu.ZIEKEiw0PNZTcHX7AEEVgJ6/Qz1Hq.', 600),
('Elza e Guilherme Financeira Ltda', 'J', '543.140.070-36', '11.282.554/0001-45', 'elzaeguilhermefinanceira@teste.com.br', '$2y$10$ly02Lm8fXoqKcTYKYBK38OCiKzsAtC1a8XSIfJXT7SQdESyQUrXLy', 2000),
('Caio e Juan Doces & Salgados Ltda', 'J', '119.991.960-82', '81.176.596/0001-87', 'caioejuansalgados@teste.com.br', '$2y$10$6lNDGCE1aqWORebMF4TNmuCIwkfovA2U4y.ZK2zU5HUezQtPBJxDi', 1500);
-- -----------------------------------------------------
-- Table `microservice`.`user_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microservice`.`user_transactions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `payer` BIGINT(20) UNSIGNED NOT NULL COMMENT 'ID do usuário que está pagando.',
  `payee` BIGINT(20) UNSIGNED NOT NULL COMMENT 'ID do usuário que está recebendo.',
  `status` ENUM('0', '1', '2') NOT NULL DEFAULT '0' COMMENT '0 = Pendente; 1 = Concluída; 2 = Estornada',
  `amount` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_transactions_users1_idx` (`payer` ASC) ,
  INDEX `fk_user_transactions_users2_idx` (`payee` ASC) ,
  CONSTRAINT `fk_user_transactions_users1`
    FOREIGN KEY (`payer`)
    REFERENCES `microservice`.`users` (`id`),
  CONSTRAINT `fk_user_transactions_users2`
    FOREIGN KEY (`payee`)
    REFERENCES `microservice`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

INSERT INTO `microservice`.`users` (`fullname`, `type`, `cpf`, `cnpj`, `email`, `password`, `wallet`)
VALUES
('João Pedro Oliveira', 'F', '654.495.480-28', NULL, 'jpoliveira@teste.com.br', '$2y$10$lI9tj99Js1db/TkFGLKhLOM0bnUt1YmhqzQnqP79R9qHbNsr2u7xq', 250),
('Mauro Silva Pereira', 'F', '545.381.810-72', NULL, 'maurosilva@teste.com.br', '$2y$10$ykN/ZPOxcrGwSOH8hgNdfef/dhAWJTfVAc7qTsE9HiXIVRaYnLKGi', 0),
('Daniele Batista', 'F', '381.707.060-84', NULL, 'danibatista@teste.com.br', '$2y$10$egZ9uF3rwvN/Yz15.KBmJePtfPP4LGGggr115dMjBbZlm4Z2WvnGC', 450),
('Andrea e Cecília Lavanderia Ltda', 'J', '913.002.330-01', '97.738.582/0001-40', 'andreaececilialavanderia@teste.com.br', '$2y$10$Hbq2BVxfeVlVncQuigqjgu.ZIEKEiw0PNZTcHX7AEEVgJ6/Qz1Hq.', 600),
('Elza e Guilherme Financeira Ltda', 'J', '543.140.070-36', '11.282.554/0001-45', 'elzaeguilhermefinanceira@teste.com.br', '$2y$10$ly02Lm8fXoqKcTYKYBK38OCiKzsAtC1a8XSIfJXT7SQdESyQUrXLy', 2000),
('Caio e Juan Doces & Salgados Ltda', 'J', '119.991.960-82', '81.176.596/0001-87', 'caioejuansalgados@teste.com.br', '$2y$10$6lNDGCE1aqWORebMF4TNmuCIwkfovA2U4y.ZK2zU5HUezQtPBJxDi', 1500);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
